model: compression-lp
dataset: WN18
epochs: 1000
learn_rate: 0.001
hid_units : 16
latent_size: 128
neg_sample_rate: 1
optimiser: adam
weight_decay: 0.0
dropout: 0.6
decomposition:
  type: block
  num_blocks: 1
edge_dropout:
  general: 0.2
  self_loop: 0.4
eval_every: 10
use_cuda: True