model: standard-lp
dataset: FB15k-237
epochs: 10000
learn_rate: 0.01
rgc_layer: 2
hid_units: 500
embedding_size: 500
neg_sample_rate: 10
optimiser: adam
weight_decay: 0.0
dropout: 0.6
decomposition:
  type: basis
  num_blocks: 5
edge_dropout:
  general: 0.2
  self_loop: 0.4
eval_every: 10
use_cuda: True
