model: standard-lp
dataset: WN18
epochs: 10000
learn_rate: 0.01
rgc_layer: 1
hid_units: 200
neg_sample_rate: 1
optimiser: adam
weight_decay: 0.0
dropout: 0.6
decomposition:
  type: basis
  num_bases: 2
edge_dropout:
  general: 0.2
  self_loop: 0.4
eval_every: 10
use_cuda: True
